from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime

def generate_payslip_pdf(payroll_data, employee_data):
    """Generate payslip PDF for an employee"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        spaceAfter=30,
        alignment=1  # Center alignment
    )
    story.append(Paragraph("PAYSLIP", title_style))
    story.append(Spacer(1, 12))

    # Company Header
    company_style = ParagraphStyle(
        'Company',
        parent=styles['Normal'],
        fontSize=14,
        alignment=1,
        spaceAfter=20
    )
    story.append(Paragraph("HRMS Company", company_style))
    story.append(Paragraph("Employee Management System", company_style))
    story.append(Spacer(1, 20))

    # Employee Details
    emp_details = [
        ["Employee ID:", employee_data.get('employee_id', 'N/A')],
        ["Employee Name:", employee_data.get('full_name', 'N/A')],
        ["Department:", employee_data.get('department', 'N/A')],
        ["Designation:", employee_data.get('designation', 'N/A')],
        ["Pay Period:", f"{payroll_data.get('payroll_month', 'N/A')}"],
        ["Generated Date:", datetime.now().strftime("%Y-%m-%d")]
    ]

    emp_table = Table(emp_details, colWidths=[2*inch, 4*inch])
    emp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(emp_table)
    story.append(Spacer(1, 20))

    # Salary Details
    salary_data = [
        ["Earnings", ""],
        ["Basic Salary", f"₹{payroll_data.get('basic_salary', 0):,.2f}"],
        ["Allowances", f"₹{payroll_data.get('allowances', 0):,.2f}"],
        ["", ""],
        ["Deductions", ""],
        ["Tax", f"₹{payroll_data.get('tax', 0):,.2f}"],
        ["PF", f"₹{payroll_data.get('pf', 0):,.2f}"],
        ["Other Deductions", f"₹{payroll_data.get('deductions', 0):,.2f}"],
        ["", ""],
        ["Net Salary", f"₹{payroll_data.get('net_salary', 0):,.2f}"]
    ]

    salary_table = Table(salary_data, colWidths=[3*inch, 3*inch])
    salary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
        ('BACKGROUND', (0, 4), (-1, 4), colors.lightcoral),
        ('BACKGROUND', (0, -1), (-1, -1), colors.lightgreen),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 4), (-1, 4), 'Helvetica-Bold'),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('SPAN', (0, 1), (1, 1)),
        ('SPAN', (0, 2), (1, 2)),
        ('SPAN', (0, 5), (1, 5)),
        ('SPAN', (0, 6), (1, 6)),
        ('SPAN', (0, 7), (1, 7)),
        ('SPAN', (0, 9), (1, 9))
    ]))
    story.append(salary_table)
    story.append(Spacer(1, 20))

    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        alignment=1,
        spaceAfter=10
    )
    story.append(Paragraph("This is a computer generated payslip.", footer_style))
    story.append(Paragraph("Generated by HRMS System", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer


def generate_attendance_report_pdf(attendance_data, employee_data):
    """Generate attendance report PDF"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=1
    )
    story.append(Paragraph("Monthly Attendance Report", title_style))
    story.append(Spacer(1, 12))

    # Employee Details
    emp_details = [
        ["Employee ID:", employee_data.get('employee_id', 'N/A')],
        ["Employee Name:", employee_data.get('full_name', 'N/A')],
        ["Department:", employee_data.get('department', 'N/A')],
        ["Month/Year:", f"{attendance_data.get('month', 'N/A')}/{attendance_data.get('year', 'N/A')}"],
        ["Generated Date:", datetime.now().strftime("%Y-%m-%d")]
    ]

    emp_table = Table(emp_details, colWidths=[2*inch, 4*inch])
    emp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(emp_table)
    story.append(Spacer(1, 20))

    # Attendance Summary
    summary_data = [
        ["Total Working Days", attendance_data.get('total_working_days', 0)],
        ["Present Days", attendance_data.get('present_days', 0)],
        ["Absent Days", attendance_data.get('absent_days', 0)],
        ["Half Days", attendance_data.get('half_days', 0)],
        ["Leave Days", attendance_data.get('leave_days', 0)],
        ["Late Marks", attendance_data.get('late_marks', 0)],
        ["Overtime Hours", attendance_data.get('total_overtime_hours', 0)],
        ["Attendance Percentage", f"{attendance_data.get('attendance_percentage', 0):.2f}%"]
    ]

    summary_table = Table(summary_data, colWidths=[3*inch, 3*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(summary_table)

    doc.build(story)
    buffer.seek(0)
    return buffer
